info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  title: Swagger API
  version: "1.0"
paths:
  /wolf/rbac/access_check:
    get:
      consumes:
      - application/json
      description: apisix登陆与权限校验，必须实现
      operationId: get-string-by-int
      produces:
      - application/json
      summary: 访问校验
swagger: "2.0"
